name: Deploy to VPS

on:
  push:
    branches:
      - main # Run deployment when pushing to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H your-vps-ip >> ~/.ssh/known_hosts

      - name: Deploy to VPS
        run: |
          ssh root@149.255.39.32 << 'EOF'
            cd /var/www/intranet-server
            git stash
            git pull origin main
            npm install
            pm2 restart all  # Restart Node.js app
          EOF
